### ISSUE TITLE
x

### ISSUE THREAD

**Issue by ccytruss** [Wexurro/MargonemDodatki#1]
na twoim miejscu wyrzucilbym chodzenie z tego, bo antybot sprawdza token przy uzyciu autogoto i jezeli jest wywolywane funkcja taka jak twoja to moze cos wykryc

**Comment by Wexurro** [comment]
Dzięki za informacje, skrypt zostawie, dam stosowną informacje na temat tego

**Comment by Wexurro** [comment]
Jeżeli ruch jest wykonywany po kliknięciu to antybot nie będzie tego wykrywał. Antybot wykrywa ruch wykonywany bez użycia klawiatury lub myszy.
